security:
    encoders:
        Symfony\Component\Security\Core\User\UserInterface:
            id: App\Security\PasswordEncoder\ScryptPasswordEncoder
    providers:
        user_entity:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: user_entity
            anonymous: true
            stateless: true
            guard:
                authenticators:
                    - App\Security\Guard\BasicGuardAuthenticator
    access_control:
        - { path: '^/users', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/', roles: IS_AUTHENTICATED_FULLY }
