# Auth with HTTP-Basic and retrieve Token cookie session for other requests auth.
POST http://localhost:8000/sessions
Accept: application/json
Authorization: Basic toto password

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "status not 200");
});
client.global.set("session_cookie_token", response.body.token_id);
%}

###

# Create a Space with token-based session-cookie auth
POST http://localhost:8000/spaces
Content-Type: application/json
Accept: application/json
X-CSRF-Token: {{session_cookie_token}}toto

{
    "name": "space name",
    "owner": "toto"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "status not 201");
});
%}

###
